FROM python:3.11-slim
WORKDIR /app/grpc_server
# Install only what's needed for gRPC server
RUN pip install --no-cache-dir grpcio>=1.75.1
COPY . /app/grpc_server
EXPOSE 50051
CMD ["python", "server.py"]
